### ISSUE TITLE
Paper tape reader

### ISSUE THREAD

**Issue by justfortestkamy** [slu4coder/YouTube#1]
I would very much like to know how your paper tape reader works! Please if possible make a video about how you made it and how it works. It is very interesting that the computer reads its program from a piece of paper.
Thank you so much for making such videos! they are very valuable.

**Comment by slu4coder** [comment]
Building the reader was a fun project but it wasn't quite "future-proof" since it is only feasible to produce very short programs. Anything else is so much work. Just like in the old days, though. The reader itself was quite simple, just a row of LEDs with adjacent photo diodes measuring light transmission. The Arduino sketch was a bit tricky though (coping with ambient light and uneven transmission at paper joinst etc.). I might play with this idea again and build something for my "Minimal 64 Home Computer". Check it out on YouTube. Cheers!

**Comment by justfortestkamy** [comment]
I have some interesting ideas about these topics. Is there a better way to talk about it?
